// ESLint flat config (ESLint v10). Tailored to this repo's two very different
// JS worlds:
//
//   js/*.js   - the UI layer. These files are NOT ES modules: scripts/concat.mjs
//               concatenates them into ONE shared-scope IIFE, so a function
//               declared in 01-core.js is legitimately referenced in 08-salary.js.
//               Linting them individually means `no-undef` would fire on ~350
//               legitimate cross-file references, so it's disabled HERE ONLY.
//               Everything else that catches real bugs regardless of scope
//               (unused vars, duplicate keys, unreachable code, etc.) stays on.
//
//   src/core/*.js - the tested financial core. These ARE real ES modules with
//               clean imports/exports, so they get the strict treatment,
//               including no-undef.
//
// Run: `npm run lint` (check) / `npm run lint:fix` (autofix).
import js from "@eslint/js";
import globals from "globals";

export default [
  // ---- global ignores ----
  {
    ignores: [
      "node_modules/**",
      "dist/**",
      "coverage/**",
      "src/app-core.generated.js", // AUTO-GENERATED by concat.mjs
      "public/**", // fetched data + vendored assets
    ],
  },

  // ---- baseline recommended rules for everything ----
  js.configs.recommended,

  // ---- UI layer: shared-scope scripts (js/*.js) ----
  {
    files: ["js/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: {
        ...globals.browser,
        // The UI bundle talks to the tested core via this global (set by
        // src/core-bridge.js before the bundle runs).
        __core: "readonly",
        // Injected at build time by Vite's `define` (see vite.config.js).
        __APP_VERSION__: "readonly",
        // Charting lib loaded via <script> in index.html.
        Highcharts: "readonly",
      },
    },
    rules: {
      // Cross-file shared-scope references make these unworkable per-file.
      "no-undef": "off",
      "no-redeclare": "off", // same symbol can appear across concatenated files
      // The first-pass backlog is now at ZERO (see PR #30), so these rules are
      // promoted from "warn" to "error": CI fails on any NEW violation rather
      // than letting a fresh backlog accumulate. Options are unchanged.
      "no-unused-vars": [
        "error",
        {
          args: "none",
          vars: "local",
          ignoreRestSiblings: true,
          caughtErrors: "none", // `catch (_e)` / `catch (e)` unused is fine
        },
      ],
      "no-empty": ["error", { allowEmptyCatch: true }], // empty catch is a known pattern here
      eqeqeq: ["error", "smart"],
      "no-var": "off", // legacy style in parts of the UI; not worth churning now
      "prefer-const": "off",
      // Promoted to error -> all currently clean across js/*.js:
      "no-cond-assign": "error",
      "no-constant-condition": "error",
      "no-useless-escape": "error",
      "no-prototype-builtins": "error",
      "no-control-regex": "error",
      "no-fallthrough": "error",
      "no-irregular-whitespace": "error",
      "no-misleading-character-class": "error",
      "no-sparse-arrays": "error",
      "no-async-promise-executor": "error",
      // Fires on `let x = null` reassigned before use. Backlog cleared, so error.
      "no-useless-assignment": "error",
    },
  },

  // ---- tested core: real ES modules ----
  // Clean modules with real imports/exports and a full test suite. The two
  // ESLint v10 rules this pre-existing code tripped (no-useless-assignment,
  // preserve-caught-error) were cleared in PR #30, so the whole block is now
  // strict (error): the tested core must stay lint-clean.
  {
    files: ["src/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: { ...globals.browser, __core: "readonly" },
    },
    rules: {
      "no-unused-vars": [
        "error",
        {
          args: "none",
          ignoreRestSiblings: true,
          caughtErrors: "none", // allow `catch (_e)` with unused binding
        },
      ],
      eqeqeq: ["error", "smart"],
      "no-useless-assignment": "error",
      "preserve-caught-error": "error",
    },
  },

  // ---- tests (vitest) ----
  {
    files: ["test/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        ...globals.node,
        ...globals.browser, // jsdom-env tests use document/window/localStorage
        describe: "readonly",
        it: "readonly",
        test: "readonly",
        expect: "readonly",
        beforeEach: "readonly",
        afterEach: "readonly",
        beforeAll: "readonly",
        afterAll: "readonly",
        vi: "readonly",
      },
    },
    rules: {
      // `ignoreRestSiblings` lets a test deliberately destructure fields purely
      // to strip them from a `...rest` (e.g. backup-crypto peels the opaque
      // salt/iv/ct off the envelope so it can assert no plaintext leaks into the
      // structural remainder) without tripping unused-var errors. Promoted to
      // error now the backlog is clear (PR #30).
      "no-unused-vars": ["error", { ignoreRestSiblings: true }],
    },
  },

  // ---- node tooling (build scripts, vite config) ----
  {
    files: ["scripts/**/*.mjs", "*.config.js", "*.config.mjs"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: { ...globals.node },
    },
    rules: {
      // `catch (_e)` with an unused binding is used throughout the fetch
      // scripts; don't fail on it (consistent with the rest of the config).
      // Promoted to error (backlog clear, PR #30); caughtErrors:"none" keeps the
      // intentional unused catch bindings allowed.
      "no-unused-vars": [
        "error",
        { args: "none", caughtErrors: "none", ignoreRestSiblings: true },
      ],
    },
  },
];
