// ESLint flat config (ESLint v10). Tailored to this repo's two very different
// JS worlds:
//
//   js/*.js   - the UI layer. These files are NOT ES modules: scripts/concat.mjs
//               concatenates them into ONE shared-scope IIFE, so a function
//               declared in 01-core.js is legitimately referenced in 08-salary.js.
//               Linting them individually means `no-undef` would fire on ~350
//               legitimate cross-file references, so it's disabled HERE ONLY.
//               Everything else that catches real bugs regardless of scope
//               (unused vars, duplicate keys, unreachable code, etc.) stays on.
//
//   src/core/*.js - the tested financial core. These ARE real ES modules with
//               clean imports/exports, so they get the strict treatment,
//               including no-undef.
//
// Run: `npm run lint` (check) / `npm run lint:fix` (autofix).
import js from "@eslint/js";
import globals from "globals";

export default [
  // ---- global ignores ----
  {
    ignores: [
      "node_modules/**",
      "dist/**",
      "coverage/**",
      "src/app-core.generated.js", // AUTO-GENERATED by concat.mjs
      "public/**", // fetched data + vendored assets
    ],
  },

  // ---- baseline recommended rules for everything ----
  js.configs.recommended,

  // ---- UI layer: shared-scope scripts (js/*.js) ----
  {
    files: ["js/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: {
        ...globals.browser,
        // The UI bundle talks to the tested core via this global (set by
        // src/core-bridge.js before the bundle runs).
        __core: "readonly",
        // Injected at build time by Vite's `define` (see vite.config.js).
        __APP_VERSION__: "readonly",
        // Charting lib loaded via <script> in index.html.
        Highcharts: "readonly",
      },
    },
    rules: {
      // Cross-file shared-scope references make these unworkable per-file.
      "no-undef": "off",
      "no-redeclare": "off", // same symbol can appear across concatenated files
      // FIRST-PASS POLICY for the UI layer: surface findings as WARNINGS, not
      // errors, so adopting the linter doesn't turn CI red on 22k lines of
      // working legacy code. The lint CI job only fails on ERRORS, so this lets
      // us see the backlog and burn it down incrementally, then promote rules
      // to "error" later. (src/core stays strict - see its block below.)
      "no-unused-vars": [
        "warn",
        {
          args: "none",
          vars: "local",
          ignoreRestSiblings: true,
          caughtErrors: "none", // `catch (_e)` / `catch (e)` unused is fine
        },
      ],
      "no-empty": ["warn", { allowEmptyCatch: true }], // empty catch is a known pattern here
      eqeqeq: ["warn", "smart"],
      "no-var": "off", // legacy style in parts of the UI; not worth churning now
      "prefer-const": "off",
      // Downgrade the recommended rules that can legitimately appear in
      // loose-but-correct UI code from error -> warn, so the first run is
      // informational rather than a hard failure:
      "no-cond-assign": "warn",
      "no-constant-condition": "warn",
      "no-useless-escape": "warn",
      "no-prototype-builtins": "warn",
      "no-control-regex": "warn",
      "no-fallthrough": "warn",
      "no-irregular-whitespace": "warn",
      "no-misleading-character-class": "warn",
      "no-sparse-arrays": "warn",
      "no-async-promise-executor": "warn",
      // New in ESLint v10 recommended; fires on `let x = null` later reassigned
      // before use (harmless style, common in the signals code). Warn for now.
      "no-useless-assignment": "warn",
    },
  },

  // ---- tested core: real ES modules ----
  // Stricter than the UI (these are clean modules with real imports/exports and
  // 267 passing tests), but ESLint v10's recommended set added NEW error-level
  // rules (no-useless-assignment, preserve-caught-error) that this pre-existing
  // code predates. Keep the first pass non-disruptive by warning on those
  // (and on unused vars / caught-but-unused `_e`) rather than failing CI, same
  // policy as the UI block. These can be promoted to "error" in a cleanup PR.
  {
    files: ["src/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: { ...globals.browser, __core: "readonly" },
    },
    rules: {
      "no-unused-vars": [
        "warn",
        {
          args: "none",
          ignoreRestSiblings: true,
          caughtErrors: "none", // allow `catch (_e)` with unused binding
        },
      ],
      eqeqeq: ["warn", "smart"],
      "no-useless-assignment": "warn",
      "preserve-caught-error": "warn",
    },
  },

  // ---- tests (vitest) ----
  {
    files: ["test/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        ...globals.node,
        describe: "readonly",
        it: "readonly",
        test: "readonly",
        expect: "readonly",
        beforeEach: "readonly",
        afterEach: "readonly",
        beforeAll: "readonly",
        afterAll: "readonly",
        vi: "readonly",
      },
    },
    rules: {
      "no-unused-vars": "warn",
    },
  },

  // ---- node tooling (build scripts, vite config) ----
  {
    files: ["scripts/**/*.mjs", "*.config.js", "*.config.mjs"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: { ...globals.node },
    },
    rules: {
      // `catch (_e)` with an unused binding is used throughout the fetch
      // scripts; don't fail on it (consistent with the rest of the config).
      "no-unused-vars": [
        "warn",
        { args: "none", caughtErrors: "none", ignoreRestSiblings: true },
      ],
    },
  },
];
