// Build step: concatenate the 9 ordered UI source files into
// src/app-core.generated.js (a single shared-scope script) which Vite bundles.
//
// v2 note: the fee/tax/FIFO MATH lives in tested ES modules under src/core/.
// The UI files here delegate to them via globalThis.__core (set by
// src/core-bridge.js, which main.js imports BEFORE this bundle). The UI keeps
// its shared-scope model so its ~350 cross-file references stay intact.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const jsDir = join(root, "js");

const files = [
  "01-core.js",
  "02-compute.js",
  "03-signals.js",
  "04-render.js",
  "05-rebalance.js",
  "06-features.js",
  "07-expenses.js",
  "08-salary.js",
  "09-boot.js",
];

const parts = files.map((f) => {
  const text = readFileSync(join(jsDir, f), "utf8");
  return `\n// ===== ${f} =====\n${text}`;
});

// Wrap the whole thing in one IIFE so the shared scope is a single function
// scope (module-safe: does not leak to other modules, but all 9 parts see
// each other's top-level declarations - identical to the original app).
const banner =
  "// AUTO-GENERATED by scripts/concat.mjs from js/01..09-*.js - DO NOT EDIT.\n" +
  "// Edit the numbered source files instead, then run `npm run build`.\n";

const body = parts.join("\n");

// The original app ran as a NON-module top-level script, so its functions were
// true globals - reachable from inline onclick="..." handlers in generated HTML.
// Wrapping the code in an IIFE (or loading as an ES module) makes top-level
// `function foo(){}` private. Most inline-handler targets already do
// `window.foo = ...`, but these 16 are bare declarations. Re-publish them to
// `window` so inline handlers keep working. (Additive only; no logic changes.)
// These bare (non-window) functions are targets of data-act handlers in the
// generated HTML. The delegated dispatcher (09-boot.js) looks up window[name],
// so they must be published to window. (window.* handlers like delTxn are
// already global via their own assignment.)
const EXPOSE = [
  "gotoTab",
  "clearTbSel",
  "toggleTbSel",
  "openDraftSelected",
  "applyDraftAll",
  "recalcDraftSel",
  "commitDraftSelected",
  "closeDraftSelected",
  "rbDraftOne",
  "rbDraftAll",
  "renderDivCalGrid",
  "divCalPrevMonth",
  "divCalNextMonth",
  "editCashRow",
  "deleteCashRow",
  "eAddLoanDraw",
  "eDelLoanDraw",
  "eToggleLoanDraws",
];
const exposeBlock =
  "\n// ---- expose inline-handler targets to window (see note in concat.mjs) ----\n" +
  EXPOSE.map((n) => `if (typeof ${n} === "function") window.${n} = ${n};`).join(
    "\n",
  ) +
  "\n";

const out = `${banner}(function () {\n${body}\n${exposeBlock}})();\n`;

const outDir = join(root, "src");
mkdirSync(outDir, { recursive: true });
const outPath = join(outDir, "app-core.generated.js");
writeFileSync(outPath, out, "utf8");
console.log(
  `concat: wrote ${outPath} (${out.length} bytes from ${files.length} files)`,
);
